name: Build a Nodejs App and push to docker hub

on:
  push:
    branches:
      -main
  workflow_dispatch:

jobs:
  build-and-push:
    name: node to docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18.x', '20.x', '22.x']
        os: [ubuntu-latest, window-latest, macOS-latest]
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4
      - name: Set up nodejs
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install frontend dependencies
        run: |
          cd dive-react-app
          npm install
          npm run lint
          npm run build
      
 
